import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  text: {
    color: 'black',
    textAlign: 'center',
    fontSize: 15,
    alignSelf: 'center',
    fontWeight: '500',
  },
  imageView: {
    display: 'flex',
  },
  image: {
    borderRadius: 100,
    height: 96,
    width: 96,
    marginTop: 38,
    marginLeft: 16,
    marginRight: 263,
  },
  profileName: {
    color: '#000',
    fontSize: 22,
    marginLeft: 15,
    marginTop: 12,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  email: {
    fontSize: 15,
    marginLeft: 16,
    marginTop: 4,
    marginBottom: 4,
    color: 'gray',
  },
  profileEdit: {
    fontSize: 17,
    marginLeft: 12,
    marginTop: 4,
    color: '#1E7BF6',
    height: 20,
    marginRight: 18,
  },
  editProfile: {
    display: 'flex',
    flexDirection: 'row-reverse',
    marginTop: -22,
  },
  options: {
    height: 50,
    borderColor: 'grey',
    borderWidth: 0.5,
    marginHorizontal: 10,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 5,
  },
  optionName: {
    color: 'black',
    fontSize: 15,
  },
  logout: {
    // marginTop: 30,
    position: 'absolute',
    bottom: 0,
  },
  cameraIcon: {
    height: 34,
    width: 34,
    marginTop: -30,
    marginLeft: 75,
    color: '#1E7BF6',
  },
  backIcon: {
    width: 25,
    height: 25,
    marginHorizontal: 10,
  },
  emailIcon: {
    fontsize: 29,
    width: 20,
    height: 20,
    left: 126,
    top: 7,
    color: '#1E7BF6',

    // paddingRight: 3,
  },
  wallet: {
    width: 15,
    height: 15,
    marginHorizontal: 10,
  },
  subs: {
    width: 18,
    height: 14,
    top: 26,
    left: 10,
  },
  card: {
    width: 18,
    height: 14,
    top: 26,
    left: 10,
  },
  notification: {
    width: 18,
    height: 17,
    top: 30,
    left: 10,
  },
  changePassword: {
    width: 18,
    height: 17,
    top: 30,
    left: 10,
  },
  Logout: {
    width: 25,
    height: 25,
    top: 28,
    left: -20,
  },
  logOutText: {
    marginHorizontal: 30,
  },
  logoutName: {
    color: 'black',
    fontSize: 17,
    marginHorizontal: 10,
    marginVertical: 5,
  },
  forward: {
    height: 15,
    width: 10,
    marginHorizontal: 10,
  },
  dotsIcon: {
    width: 25,
    height: 25,
    marginHorizontal: 10,
  },
  dots: {
    flexDirection: 'row-reverse',
    display: 'flex',
  },
  mainview: {
    width: '100%',
    height: '65%',
    borderTopWidth: 1,
    borderTopColor: 'grey',
    marginTop: 2,
    backgroundColor: '#fff',
    paddingTop: 25,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  fieldview: {
    width: '90%',
    height: 50,
    borderWidth: 1,
    borderColor: '#00000080',
    borderRadius: 10,
    paddingLeft: 10,
    justifyContent: 'center',
    marginTop: 10,
    alignSelf: 'center',
  },
  attributeheading: {
    paddingLeft: 20,
    fontWeight: 'bold',
    fontSize: 18,
    paddingVertical: 5,
    color: '#00000080',
  },
  attributevalue: {
    color: '#00000080',
  },
});
export default styles;
